project_id = "read-together"

[api]
enabled = true
port = 58321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 58322
shadow_port = 58320
major_version = 17

[db.seed]
enabled = false

[realtime]
enabled = true

[studio]
enabled = false
port = 58323

[local_smtp]
enabled = false
port = 58324

[storage]
enabled = true
file_size_limit = "25MiB"

[auth]
enabled = true
site_url = "http://localhost:3000"

[analytics]
enabled = false


